name: Deploy SDK to Expo

on:
  push:
    branches:
      - main 
  workflow_dispatch:  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Login to Expo
        run: npx expo login --token ${{ secrets.EXPO_TOKEN }}

      - name: Publish to Expo
        run: npm run publish
